# Plugins
gems:
- jekyll-sitemap
- jekyll-seo-tag
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Android Makers Paris 2017"
email: "contact@androidmakers.fr"
description: "Android Makers Paris, the biggest Android event in France, 10-11th april, 2017."
baseurl: ""
url: "http://androidmakers.fr"
permalink: "/blog/:title"
googleMapApiKey: AIzaSyDoDM9sRSk2C3JeopyW7UqGRA31QLi77tw
twitter:
  username: androidmakersfr
logo: "/img/seo/organizer-logo.png"

# Organizer Info
organizerName: "Paris Android User Group & BeMyApp"
organizerAlternateName: "Paris Android User Group & BeMyApp"
organizerDescription: ""
organizerEmail: "contact@androidmakers.fr"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://paug.fr/"

# Head
metaKeywords: "event, gdg, droidcon, google, programming, android, wear, iot, glass, tv, developers, paris, makers"
twitterAccount: "@AndroidMakersFR"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://cfp.androidmakers.fr"
c4sponsorsUrl: "mailto:jeremy@bemyapp.com"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/speakers/", text: "Speakers & Talks"}
 - {permalink: "/blog/", text: "Blog"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/android-makers-1st-edition-tickets-29579435889", text: "Get your ticket"}
 - {link: "http://cfp.androidmakers.fr", text: "Become a speaker"}
 - {link: "mailto:jeremy@bemyapp.com", text: "Become a sponsor"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/android-makers-1st-edition-tickets-29579435889", text: "Get your ticket"}
 - {link: "http://cfp.androidmakers.fr", text: "Become a speaker"}
 - {link: "mailto:jeremy@bemyapp.com", text: "Become a sponsor"}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 10
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Android Makers <typeout> 2017"
eventDate: "10th & 11th april, 2017"
typeoutTextValues: '"", "France", "Paris"'
typeoutFallback: "Paris"
heroButtons:
 - {link: "https://www.eventbrite.com/e/android-makers-1st-edition-tickets-29579435889", text: "Get your ticket"}
 - {link: "http://cfp.androidmakers.fr", text: "Become a speaker"}
 - {link: "mailto:jeremy@bemyapp.com", text: "Become a sponsor"}

# About Block
aboutTitle: "Much more than a conference"
aboutDetails: "Join us in tackling the future of Android with the hottest experts of the domain.<br />There'll be technical sessions, workshops, debates, networking, plus a chance to demo your project in the Makers Area.<br />The 1st edition of Android Makers gathers 4 events in 1."
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "40min Tech Talks by awesome speakers and 20min Lightning Talks on the future of Android." }
 - {title: "Workshop", image: "barcamp.jpg", text: "Get trained on new methods, discover and build your app during the workshops." }
 - {title: "Makers Area", image: "makersarea.jpg", text: "Walk around, play and discover the latest innovation in hardware and software developed by the makers." }
 - {title: "Party!", image: "party.jpg", text: "Let’s meet, talk, drink and party!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "600", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Android content"}
 - {count: "50", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "10", specialCharacter: "+", info: "makers", detail: "crafting the future"}

# Latest News Block
latestNewsTitle: "Latest news"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Les salons de l'Aveyron"
eventLocationLink: "http://www.salonsdelaveyron.fr/"
eventStreetAddress: "17 Rue de l'Aubrac"
eventAddressLocality: "Paris"
eventAddressLocalityRegion: "Ile de France"
eventPostalCode: "75012"
eventAddressCountry: "France"
eventStartTime: "2017-04-10T09:00"
eventDoorTime: "09:00"
eventEndTime: "2017-04-11T20:00"
eventPlaceCoordinates: "48.834894, 2.386499"
mapCenterCoordinates: "48.834894, 2.386499"
mapMobileCenterCoordinates: "48.834894, 2.386499"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Les salons de l'Aveyron"
venueFeatures: ["1300m<sup>2</sup> of modulable spaces", "an 800 attendees keynote room", "Close to Bercy and Gare de Lyon, in Paris."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterFeed: "http://cmoatoto.fr/tweetledee/favoritesjson.php?c=100&cache_interval=90&user=AndroidMakersFR"
twitterHashTag: "AndroidMakersFR"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "€"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "€"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "€"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+DroidconParis", icon: "google-plus"}
 - {link: "https://twitter.com/AndroidMakersFR", icon: "twitter"}
 - {link: "https://www.facebook.com/events/700985966748191/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.paug.fr/", text: "PAUG.fr"}
   - {link: "http://bemyapp.com", text: "bemyapp.com"}
   - {link: "https://drive.google.com/drive/folders/0B6SH_S_lcnHEcFhqTzMtZGdzdjA", text: "Press"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@androidmakers.fr", text: "contact@androidmakers.fr"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "androidmakersfr"

# Thanks for Register
thanksForRegisterTitle: "Congratulations!"
thanksForRegisterDescription: "Your registration to Android Makers, April 10th-11th has been confirmed.<br /><br />For any other information, shoot us an email at <a href=mailto:contact@androidmakers.fr>contact@androidmakers.fr</a><br /><br />See you soon!"

# Analytics
googleAnalyticsTrackingId: "UA-75184420-32"
googleAnalyticsSiteUrl: "auto"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "48.834894, 2.386499"
logisticsMapMobileCenterCoordinates: "48.834894, 2.386499"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Paris"
directionDetailsCards:
 - {title: "From the Airports", information: 'Airports are close to Paris. It is easily reachable by car, public transport, Uber or taxi. You can find your way with <a href="http://www.ratp.fr/en/upload/docs/application/pdf/2014-07/depliant_aeroports_2014.pdf" target="_blank">this document</a>. You can also find the best way from <a href="http://www.ratp.fr/itineraires/fr/ratp/recherche-avancee?start=A%C3%A9roport+d%27Orly+Sud%2C+Paray-Vieille-Poste&end=17%2C+Rue+de+l%27Aubrac%2C+75012%2C+Paris" target="_blank">Orly</a> or from <a href="http://www.ratp.fr/itineraires/fr/ratp/recherche-avancee?start=A%C3%A9roport+Charles+De+Gaulle+1+%28RER%29%2C+Tremblay-en-France&end=17%2C+Rue+de+l%27Aubrac%2C+75012%2C+Paris" target="_blank">Roissy Charles De Gaulle</a>'}
 - {title: "Public Transit", information: 'Google Transit is available in Paris, so you can find most of your way in Google Maps. Moreover, you can download the official <a href="https://play.google.com/store/apps/details?id=com.fabernovel.ratp&hl=fr" target="_blank">Paris transportation application</a>.'}
 - {title: "Hotels", information: 'Paris has lots of great hotels, hostels and AirBnB. If you have any trouble to find one, you can contact us.'}
